[theme]
# BAMBOOM Brand Colors
primaryColor = "#8EA395"
backgroundColor = "#F5F2ED"
secondaryBackgroundColor = "#E6E4E0"
textColor = "#111111"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true

[browser]
gatherUsageStats = false
